channels:
  - conda-forge
dependencies:
  - python==3.11
  - pip
  - pip:
    - matplotlib
  - selectors:
    - linux-64:
      - pip:
        - --index-url https://download.pytorch.org/whl/cu118
        - torch
        - torchvision
    - osx-arm64:
      - pip:
        - torch
        - torchvision